function downloadTLE(download_path,URL,NORAD_ID,start_date,end_date, user,pass)
    post={...
      'identity',user,...
      'password',pass,...
      'query',[...
        'https://www.space-track.org/basicspacedata/',...
        'query/class/tle/',...
        'NORAD_CAT_ID/',num2str(NORAD_ID),'/',...
        'EPOCH/',start_date,'--',end_date,'/',...
        'format/tle',...
      ]...
    };

    out=urlread(URL,'Post',post,'Timeout',10);
    
    fid = fopen([download_path '\' num2str(NORAD_ID) '_' start_date '_' end_date '.txt'],'w+');
    fprintf(fid,'%s',out); 
    fclose(fid);   
    