close all
clear all
clc

user  = 'maarten.haneveer@gmail.com';
pass  = 'maartenhaneveer1990';
norad = 32789


URL='https://www.space-track.org/ajaxauth/login';

post={...
  'identity',user,...
  'password',pass,...
  'query',[...
    'https://www.space-track.org/basicspacedata/',...
    'query/class/tle/',...
    'NORAD_CAT_ID/',num2str(norad),'/',...
    'EPOCH/','2016-07-20','--','2016-07-30','/',...
    'format/tle',...
  ]...
};

out=urlread(URL,'Post',post,'Timeout',5)
  
%line1=out(1:71);
%line2=out(72:142);